### ISSUE TITLE
Weird behavior with tag button

### ISSUE THREAD

**Issue by EmarJ** [roman01la/JSONFormData#6] opened 2015-09-24 14:33 UTC
Hi there,

I'm trying to use this polyfill and I am experiencing weird behavior with `<button>` elements.

I've done some tests but I'm cannot understand exactly what's going on. I tried look at the spec to see how "button" element are handled, with no results.

My form contains bunch of `<input>` elements, all with their name attribute, and lot of `<button>` elements with **no name attribute** at all. Seems that these buttons are included in JSON string with empty label and value.

I tried to remove all buttons from page and seems working fine.

-----------

I post my html code and my output (sorry for data attributes, they don't help readability for sure):

```html
<form enctype="application/json" data-reactid=".0">
        <div class="form-field-group" id="form-title-group" data-reactid=".0.0">
            <label style="display:;" data-reactid=".0.0.0">Title:</label>
            <div class="form-group" data-reactid=".0.0.1">
                <input type="text" name="title" class="form-control" data-reactid=".0.0.1.1:$input">
            </div>
        </div>
        <div class="form-field-group" id="form-description-group" data-reactid=".0.1">
            <label style="display:;" data-reactid=".0.1.0">Description:</label>
            <div class="form-group" data-reactid=".0.1.1">
                <textarea type="textarea" name="description" class="form-control" data-reactid=".0.1.1.1:$input"></textarea>
            </div>
        </div>
        <div class="form-field-group" id="form-realization-date-group" data-reactid=".0.2">
            <label style="display:;" data-reactid=".0.2.0">Realization Date:</label>
            <div class="form-group" data-reactid=".0.2.1">
                <input type="number" name="realization-date" class="form-control" data-reactid=".0.2.1.1:$input">
            </div>
        </div>
        <div data-reactid=".0.3">
            <label data-reactid=".0.3.0">Images:</label>
            <div data-reactid=".0.3.1">
                <button type="button" class="btn btn-default" data-reactid=".0.3.1.0">
                    <span class="glyphicon glyphicon-plus" data-reactid=".0.3.1.0.0">Add</span>
                </button>
            </div>
            <ul class="list-unstyled" data-reactid=".0.3.2">
                <li class="row" data-reactid=".0.3.2.$1">
                    <div class="col-sm-4" data-reactid=".0.3.2.$1.0">
                        <input class="form-control" type="text" placeholder="Image URL" name="images[0][url]" data-reactid=".0.3.2.$1.0.0">
                    </div>
                    <div class="col-sm-4" data-reactid=".0.3.2.$1.1">
                        <input class="form-control" type="text" placeholder="Image Title" name="images[0][title]" data-reactid=".0.3.2.$1.1.0">
                    </div>
                    <div class="col-sm-4" data-reactid=".0.3.2.$1.2">
                        <button type="button" class="btn btn-default" data-reactid=".0.3.2.$1.2.0">
                            <span class="glyphicon glyphicon-minus" data-reactid=".0.3.2.$1.2.0.0">Remove</span>
                        </button>
                    </div>
                </li>
                <li class="row" data-reactid=".0.3.2.$2">
                    <div class="col-sm-4" data-reactid=".0.3.2.$2.0">
                        <input class="form-control" type="text" placeholder="Image URL" name="images[1][url]" data-reactid=".0.3.2.$2.0.0">
                    </div>
                    <div class="col-sm-4" data-reactid=".0.3.2.$2.1">
                        <input class="form-control" type="text" placeholder="Image Title" name="images[1][title]" data-reactid=".0.3.2.$2.1.0">
                    </div>
                    <div class="col-sm-4" data-reactid=".0.3.2.$2.2">
                        <button style="visibility:;" type="button" class="btn btn-default" data-reactid=".0.3.2.$2.2.0">
                            <span class="glyphicon glyphicon-minus" data-reactid=".0.3.2.$2.2.0.0">Remove</span>
                        </button>
                    </div>
                </li>
            </ul>
        </div>
        <hr data-reactid=".0.4">
        <div class="form-field-group" id="form-submit-group" data-reactid=".0.5">
            <label style="display:none;" data-reactid=".0.5.0">Submit:</label>
            <button type="reset" class="btn btn-default" data-reactid=".0.5.1:0">Cancel</button>
            <button type="button" class="btn btn-primary" data-reactid=".0.5.1:1">Submit</button>
        </div>
        <button type="button" class="btn btn-default" data-reactid=".0.6">JSON Test</button>
    </form>
```

```javascript
{"title":"","description":"","realization-date":null,"":["","","","","",""],"images":[{"url":"","title":""},{"url":"","title":""}]}
```
As you can see there is an array of empty fields.

Am I doing something wrong?

Thanks in advance

**Comment by roman01la** [comment] 2015-09-27 08:47
Hi and thanks for pointing to this issue. I believe here's the cause of the issue: https://github.com/roman01la/JSONFormData/blob/master/src/json-formdata.js#L25, this line takes all form elements, including buttons. Looking into the PR.

**Comment by roman01la** [comment] 2015-09-28 15:12
Merged. Thanks!
Build was failing because of other reasons :)

**Closed by roman01la** 2015-09-28 15:12 UTC
